### ISSUE TITLE
Include a copy of the full documentation in the repo

### ISSUE THREAD

**Issue by NgariNdungu** [gathuku/laravel_mpesa#10]
I suggest adding a copy of the documentation currently on https://beyode.co.ke/mpesa/ to say, `USAGE.md` in the repo so that the package is fully self contained.

**Comment by gathuku** [comment]
Hey @NgariNdungu  . Please make a PR. All the docs are here https://github.com/gathuku/laravel_mpesa_docs/tree/master/guide

**Comment by gathuku** [comment]
Closes by #11
