### ISSUE TITLE
can't login after creating an account with safaricom developer

### ISSUE THREAD

**Issue by hendrybones** [gathuku/laravel_mpesa#27]
Invalid Credentials
Invalid credentials. Please try again.

how can i  reset my password if don't have a chance to login

NOTE: We have migrated to the new and exciting Daraja - version 2.0 - If you experience any challenge logging in, we recommend you reset your password for a smooth transition.

**Comment by gathuku** [comment]
@hendrybones there's a link to reset the password at the end of the login form.

**Comment by hendrybones** [comment]
thanks man
